name: fludemy
description: FLUdemy.
publish_to: 'none'
version: 2.0.1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  auto_size_text: ^3.0.0
  cupertino_icons: ^1.0.8
  device_preview: ^1.2.0
  effective_dart: ^1.3.2
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
